name: xtb_env
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - black=19.10b0
  - numpy=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.7
  - rdkit=2020.03.3
  - regex=2020.6.8
  - tqdm=4.46.1
  - xtb=6.3.1
  - black
